print("hello sahara")
name = input("enter your name:")
print("welcome,sahara")
print("welcome to my first program")
age = input("enter you age:")
print("your age is 18 years old you will be 19 next year")
print("hii you are studying in first year")
college  = input("enter your college name ")
print("thankyou for letting me know about your college")
print("you will be a great programmmer")
hobby = input("enter your hobby:")
print("you have a good hobby")
a = int(input("enter a number1:"))
b =int(input("enter a number2:"))
print(a+b)
a = float(input("enter a number:"))
b = float(input("enter a number"))
print(a*b)
print("i am happy today to write a code myself")
print("thankyou for working today")
